#!/bin/bash

# wikiquotes-fortune – Generate fortune cookies from Wikiquotes
# Copyright © 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 
# Note that output from this script is derivative work of Wikiquotes
# and is therefore under the license used at Wikiquotes.


set -e -u

dateonly=0
if [ $# = 2 ]; then
  if [ "${2}" = date-only ]; then
      dateonly=1
  fi
fi

show="${1//_/ }"
show_="${show// /_}"
wiki="$(wget "http://en.wikiquote.org/wiki/${show_}" -O -)"

if [ $dateonly = 0 ]; then
    episode=
    lines=0
    
    (echo "${wiki}" |
    sed -e ':a;N;$!ba;s:<head>.*</ *head>::g' |
    grep -Po '(<h3>.*</h3>|<dl>.*</dl>|<dd>.*</dd>|<hr [^/]*/>)' |
    sed -e ':a;N;$!ba;s:\(<a [^>]*>\|</a>\)::g' |
    sed -e ':a;N;$!ba;s:\(<span [^>]*>\|</span>\)::g' |
    sed -e 's:\[edit\]::g' |
    sed -e 's:\(<[bi]>\|</[bi]>\|<dd>\|</dd>\)::g' |
    sed -e '/<label for="searchInput">Search<\/label>/d' |
    sed -e 's:<hr .*/>:<hr>:g' |
    sed -e 's:\&amp;:\&:g' |
    sed -e 's:\&#160;: :g' |
    sed -e 's/ :/:/g' ; echo "<hr>") |
    while read -r line; do
	if [ "${line::4}" = "<h3>" ]; then
	    if [ -n "${episode}" ] && (( lines > 0 )); then
		echo $'\n\t-- '"${show} - ${episode}"$'\n%'
		lines=0
	    fi
	    episode="$(echo "${line}" | sed -e 's:^<h3>\(.*\)</h3>$:\1:g')"
	elif [ "${line}" = "<hr>" ]; then
	    if (( lines > 0 )); then
		echo $'\n\t-- '"${show} - ${episode}"$'\n%'
		lines=0
	    fi
	else
	    echo "${line}"
	    lines=$(( lines + 1 ))
	fi
    done > quotes
fi

months=(January February March April May June July August September October November December)
index=1

history="$(echo "${wiki}" |
grep '\&amp;action=history' |
grep -Po 'href="[^"]*"' |
sed 's:href="\([^"]*\)":\1:g' | sed -e 's:\&amp;:\&:g')"
wget "http://en.wikiquote.org/${history}" -O - |
grep '(cur |' |
grep -Po '<a [^>]*>[^<]*</a>' | grep date |
grep -Po '>[^<]*<' |
sed -e 's/>[0-9]*:[0-9]*, \([^<]*\)</\1/' |
sed -e 's/^\([0-9]*\) \([A-Za-z]*\) \([0-9]*\)$/\3 \2 \1/g' |
for m in ${months[@]}; do
    if (( index < 10 )); then
	sed -e "s: ${m} :0${index}:"
    else
	sed -e "s: ${m} :${index}:"
    fi
    (( index++ ))
done > version

